# Stage Python source distribution and wheel packages through GitHub Actions (GHA) to Python Package Index (PyPI).
name: "Release: Python package to PyPI"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    name: Build & publish package to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Build package
        run: |
          python -m pip install build twine
          python -m build
          twine check dist/{*.tar.gz,*.whl}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
